name: Boojum build

on:
  push:
      branches: ["main", "switch-println-to-tracing-trace"]

jobs:
  boojum-build-test:
    runs-on: [ self-hosted, ci-runner ]
    
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"
      
      - name: Setup rustup
        run: |
          wget -q -O - https://sh.rustup.rs | bash -s -- -y
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
          echo "CARGO_BUILD_JOBS=$(($(nproc) /2))" >> "${GITHUB_ENV}"
          echo "export PATH=\"$HOME/.cargo/bin:\$PATH\"" >> "${HOME}/.bash_profile"
      
      - name: setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly-2023-05-31
          rustup default nightly-2023-05-31
      
      - name: build
        run: cargo +nightly-2023-05-31 build --release
